version: "3.7"

services:
  app:
    image: account-id.dkr.ecr.us-west-1.amazonaws.com/repo:latest
    command: npm install
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    volumes:
      - postgres-data:/usr/src/app

volumes:
  postgres-data: